docs: redirect questions to Github discussions
scikit-hep/pyhf pull request #1283
Opened 2021-02-01 20:23 UTC by eschanet

# Description

Fixes  #1269, by replacing links to the `pyhf` stackoverflow tag with links to the Github Discussions page of the project.

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [ ] Summarize commit messages into a comprehensive review of the PR

2021-02-01 20:31 UTC, matthewfeickert commented
Thanks for your PR @eschanet &mdash; your contributions are appreciated! Would you please [add your name to `docs/contributors.rst`](https://github.com/scikit-hep/pyhf/blob/master/CONTRIBUTING.md#pull-request-procedure)?

I'll take a look at the docs render of this and properly review it later today as well.

2021-02-02 17:56 UTC, kratsg approved these changes

2021-02-02 18:55 UTC, matthewfeickert requested changes
@eschanet Just a very small change: Github -> GitHub So I'll take care of this and push updates and then merge.

2021-02-02 18:55 UTC, matthewfeickert commented on CONTRIBUTING.md
> +If you have suggestions, questions that you can't find answers to on the [documentation website](https://scikit-hep.org/pyhf/) or in the [Github discussions](https://github.com/scikit-hep/pyhf/discus
```suggestion
If you have suggestions, questions that you can't find answers to on the [documentation website](https://scikit-hep.org/pyhf/) or in the [GitHub Discussions](https://github.com/scikit-hep/pyhf/discussions), or have found a bug please [open an Issue](https://github.com/scikit-hep/pyhf/issues/new/choose)!
```

2021-02-02 18:55 UTC, matthewfeickert commented on README.rst
> +on `Github Discussions <https://github.com/scikit-hep/pyhf/discussions>`__.
```suggestion
on `GitHub Discussions <https://github.com/scikit-hep/pyhf/discussions>`__.
```

2021-02-02 18:55 UTC, matthewfeickert commented on docs/faq.rst
> +If you have a question about the use of ``pyhf`` not covered in the `documentation <https://scikit-hep.org/pyhf/>`__, please ask a question on `Github Discussions <https://github.com/scikit-hep/pyhf/
```suggestion
If you have a question about the use of ``pyhf`` not covered in the `documentation <https://scikit-hep.org/pyhf/>`__, please ask a question on `GitHub Discussions <https://github.com/scikit-hep/pyhf/discussions>`__.
```

2021-02-02 19:53 UTC, matthewfeickert approved these changes
LGTM. :+1:

2021-02-02 19:56 UTC, merged

2021-02-02 19:57 UTC, matthewfeickert commented
Thanks very much for the PR @eschanet!