Refactor code quality issues
scikit-hep/pyhf pull request #1325
Opened 2021-02-17 23:29 UTC by akshgpt7

# Description
I ran [DeepSource](https://deepsource.io/) analysis on my fork of the repo, and found some interesting [code quality issues](https://deepsource.io/gh/akshgpt7/pyhf/) that can improve the general code quality here.
This PR fixes a few of the issues detected.

### Summary of changes:
- Refactor unnecessary use of `elif/else` after `return`.
- Simplify `if` statements to use `bool()`.
- Refactor iterating over dictionary instead of using `dict.keys()`.

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [ ] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [ ] Summarize commit messages into a comprehensive review of the PR

2021-02-18 02:46 UTC, akshgpt7 commented
@matthewfeickert The test seems to be failing for macOS when it tries to install tensorflow. Can you help me know if this is a fixable error?

2021-02-18 07:08 UTC, matthewfeickert commented
Thanks for your PR @akshgpt7! We'll take a look at this later today and get it reviewed, which should be easy enough. We're probably not interested in picking up additional config files or dependencies at the moment though, so right off the bat can we ask you to remove `.deepsource.toml`?

> The test seems to be failing for macOS ...

The VMs for GHA sometimes can be finicky for Mac. I restarted the CI.

2021-02-18 21:56 UTC, akshgpt7 commented
@matthewfeickert removed the `.deepsource.toml` file as requested.

2021-02-19 03:10 UTC, matthewfeickert requested changes
Thanks for the PR. Though this PR doesn't really deal with code quality issues, but rather is just applying changes from the scan blindly. That's fine, but some of them don't really justify the noise they would add. 

If you take out the ones that I've flagged I think we'd accept this.

2021-02-19 03:10 UTC, matthewfeickert commented on src/pyhf/optimize/__init__.py
> +        if name == 'minuit_optimizer':
This doesn't really do anything to justify the change.

2021-02-19 03:10 UTC, matthewfeickert commented on src/pyhf/tensor/__init__.py
> +        if name == 'jax_backend':
This doesn't really do anything to justify the change.

2021-02-19 03:10 UTC, matthewfeickert commented on tests/test_export.py
> +        (spec_histosys(), {}),
This doesn't really do anything to justify the change, especially as since these are tests.

2021-02-19 06:06 UTC, matthewfeickert approved these changes
Thanks. LGTM :+1:

2021-02-19 23:18 UTC, lukasheinrich approved these changes

2021-02-19 23:37 UTC, merged