check POIs floating
scikit-hep/pyhf pull request #1409
Opened 2021-04-13 21:12 UTC by lukasheinrich

# Description

This fixes #1391

2021-04-14 02:55 UTC, matthewfeickert requested changes
Thanks @lukasheinrich. This looks good overall :+1:, and I don't have any code change suggestions, just docs and exception related suggestions.

2021-04-14 02:55 UTC, matthewfeickert commented on src/pyhf/infer/utils.py
> +        pdf (:obj:`pyhf.Model`): The model
```suggestion
        pdf (~pyhf.pdf.Model): The statistical model adhering to the schema ``model.json``.
```
Would be good to match what we have elsewhere.

2021-04-14 02:55 UTC, matthewfeickert commented on src/pyhf/infer/utils.py
> +        fixed_params: array of bools
```suggestion
        fixed_params (:obj:`list` or `tensor` of :obj:`bool`): Array of :obj:`bool`s indicating if model parameters are fixed.
```

2021-04-14 02:55 UTC, matthewfeickert commented on src/pyhf/infer/utils.py
> +        bool: The result whether all POIs are floating.
```suggestion
        :obj:`bool`: The result whether all POIs are floating.
```

Giordon started defaulting to using `obj` whenever possible, and I think that's a good habit to continue.

2021-04-14 02:55 UTC, matthewfeickert commented on src/pyhf/infer/__init__.py
> +            f'POI at index [{pdf.config.poi_index}] forced to be fixed, cannot run inference'
```suggestion
            f'POI at index [{pdf.config.poi_index}] is set as fixed, which makes inference impossible. Please unfix the POI to continue.'
```

Maybe we should be super explicit? There's probably some cleaner/clearer way then what this suggestion has, but I'm just trying to indicate that we should probably be overly verbose in error messages like this.

2021-04-14 02:58 UTC, matthewfeickert commented on src/pyhf/infer/utils.py
> +    Checks whether all POI(s) are floatig (i.e. not within the fixed set).
```suggestion
    Checks whether all POI(s) are floating (i.e. not within the fixed set).
```

2021-04-14 15:14 UTC, matthewfeickert requested changes
@lukasheinrich this all LGTM, but I just realized while looking at the RTD build that this isn't getting captured in the docs. Can you add `all_pois_floating` under the Utilities section in  `docs/api.rst`?

2021-04-14 18:37 UTC, kratsg approved these changes
One note: `utils.all_pois_floating` isn't written in a generic way. Something like `not all(poi_fixed)` or similar would be best. But for now, as we only consider the case of a single POI, this is fine.

2021-04-14 19:31 UTC, lukasheinrich commented
we don't have yet the infrastructure in `_ModelConfig` for multi-POI but I purposefully names the method in a way that it's genneric so we only need to change the impl once were there

2021-04-15 04:26 UTC, matthewfeickert approved these changes
LGTM. Thanks @lukasheinrich

2021-04-15 04:27 UTC, merged