Fix: Dead objects being called through weakrefs
scikit-hep/pyhf pull request #2310
Opened 2023-08-31 09:34 UTC by wernerd-cern

# Description

The bug fixed by this PR occured in my work in the repository https://gitlab.cern.ch/dawerner/statanabenchmark.
I am currently working on a summer student project at CERN benchmarking statistical analysis tools in python including pyhf.
When performing these benchmarks, pyhf is called multiple times in a row with different backends. In some cases an error occurs then as objects are called through weakrefs that are already dead and thus `NoneType` objects.

When events (such as 'tensorlib_changed') are called, a bug occured previously where objects (i.e. the `TensorViewer`) are already dead. In this case an error occured when member functions where using attributes such as `self._sorted_indices` in `src/pyhf/tensor/common.py:33`.

This bug is fixed by catching the cases, in which the object is invalidated by earlier callbacks.
Please first read [CONTRIBUTING.md](https://github.com/scikit-hep/pyhf/tree/main/CONTRIBUTING.md).

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [ ] "WIP" removed from the title of the pull request
- [ ] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [ ] Summarize commit messages into a comprehensive review of the PR

2023-08-31 09:44 UTC, matthewfeickert requested changes
@wernerd-cern Can you [please report what the actual bug is](https://github.com/scikit-hep/pyhf/blob/main/CONTRIBUTING.md#issues) and give a reproducer as well for documentation? It would be better to make an Issue that clearly documents the bug and then have this PR close it. This PR will need tests as well.

2023-08-31 09:56 UTC, matthewfeickert commented
For reviewer reference, the last time this code was edited was in PR #1035.

2023-09-05 17:11 UTC, matthewfeickert requested changes
Seems like this is indeed needed, to be able to do what we do in our tests without providing all of `conftest.py`'s machinery. So this should go in and then a patch release made from it. :+1: 

This code doesn't have full coverage though, so appropriate tests will need to be added.

2023-09-05 17:11 UTC, matthewfeickert commented on src/pyhf/events.py
> +        for func, arg in self._callbacks:
@wernerd-cern Can you comment on why `self._callbacks` is necessary here? It seems like a different situation than with `_flush(self)` just above this function.

2023-09-05 22:45 UTC, kratsg requested changes
This PR doesn't seem to introduce any new functionality that does not already exist. `__call__` here in the changes is including changes covered by the `_flush` function. The `_flush()` should be called before trying to access the callbacks to determine the valid callbacks first. So I'm not sure how you ran into a situation that's covered by this PR that isn't already covered by the existing code...

2023-09-05 22:47 UTC, kratsg commented
In addition, the case you're describing is covered by our tests right now.

2023-09-06 01:10 UTC, matthewfeickert commented
I'm going to put this into draft until we can determine if Issue #2310 is actually reproducible.

2023-09-06 14:49 UTC, kratsg commented
> I suspect the problem is that some callbacks delete objects that owns the arguments of other callbacks, which is why flushing only at the beginning is not sufficient.

Again, this doesn't explain or change the logic. All callbacks are called through this function. Anytime you trigger the callbacks, the `_flush()` function is called, whose logic was just copied into the `__call__()` part which is already called by accessing `self.callbacks` (this got changed in the PR to access `self._callbacks` instead directly).

Without the changes, the flow is

1. switch backend
2. trigger callbacks through `__call__(self)`
3. access `self.callbacks` which triggers `self._flush()`
4. `self._flush()` removes dead refs
5. return `self.callbacks` and trigger callbacks on individual refs

With the changes, the flow is

1. switch backend
2. trigger callbacks through `self.__call__()`
3. access `self._callbacks`
4. trigger callbacks on individual refs that are not dead
5. `self._flush()` removes dead refs

Either way, `__call__` only runs on non-dead-refs. In before these changes, if a callback removes a reference to a weak ref, it will get garbage collected the next time callbacks are triggered. Which is why I'm saying that the changes aren't making a difference. The only thing that could be happening is that garbage-collection runs in between steps 4 and 5 before these changes -- which isn't currently caught, and would explain why you'd only see it if you run heavily enough to force GC to not run as frequently as it might typically do so.

2023-09-06 15:17 UTC, guitargeek commented
Thanks for making the bullet point list, maybe it's now easier for me to explain what I think is the crucial difference.

To quote the list you made and annotate with what I think is the flaw in the logic:

* switch backend

* trigger callbacks through `__call__(self)`

* access `self.callbacks` which triggers `self._flush()`

* `self._flush()` removes dead refs

* return `self.callbacks` and *iteratively* trigger *many* callbacks on individual refs, *where some of the first callbacks in the loop might drop the references on the arguments of callbacks later in the loop. The earlier call to flush has no chance of flushing these*


After the change, the flush will be called after iterating over the callbacks, catching any new dead refs that were the results of the callbacks.

2023-09-06 15:42 UTC, kratsg commented
> After the change, the flush will be called after iterating over the callbacks, catching any new dead refs that were the results of calling the callbacks.

Yes, after iterating over all callbacks, not after each one... so before the change is identical to after the change. They will get caught by the next access for callbacks before the change (delayed), but that's still ok. This is why I'm still confused. I don't see a scenario not currently caught by the original code.

2023-09-06 15:52 UTC, guitargeek commented
Here is a scenario that would not be caught by the original code:

1. There are two callbacks in the list:
      * `func_1` with `arg_1`. Calling `func_1` will delete all references to `arg_2`
      * `func_2` with `arg_2`
      Let's assume both `arg_1` and `arg_2` are not dead initially
      
2. We are calling `Callables.__call__()`, flush does nothing as there are no dead refs

3. `func_1(arg_1)` is called and there are no references to `arg_2` anymore as a result

4. `func_2` is called, but `arg_2` is now dead, resulting in an error.

I didn't dig into the pyhf code deep enough to exactly tell you what `func_1`, `func_2`, `arg_1`, and `arg_2` are, but since this scenario was the *only* was I could think of to get dead references even after flushing, I assumed that this must be happening somewhere. And indeed, when @wernerd-cern implemented the new logic that catches this case, the errors in the reproducer in #2311 go away.

2023-09-06 15:54 UTC, kratsg commented
> 4\. `func_2` is called, but `arg_2` is now dead, resulting in an error.

Ok, but again, you've been stating that moving the flush to the end catches this case when the original code does not -- this is an incorrect statement.

The difference is that you're skipping deadrefs as you iterate through the callbacks depending on if the ordering of the callbacks causes some refs to go dead during processing.

I bet if you just simply add in logic to skip refs that are dead, and remove all other changes -- that you'll catch exactly this case. Moving around the flush will do nothing though.

2023-09-06 15:59 UTC, guitargeek commented
> Ok, but again, you've been stating that moving the flush to the end catches this case when the original code does not -- this is an incorrect statement.

No, I never intended to say that (sorry if it came across like that). The position of the flush actually doesn't matter, it's all about the explicit dead arg check in the loop. We only put the flush at the end now to be a bit more efficient: like this, the flush() will also flush the new dead refs that came from calling the callbacks, so that the next time `__call__` is called it has to iterate over less elements.

You might as well put the flush also back on top.

But I'm happy we are now on the same page about skipping dead refs :+1: Sorry for not explaining explicitly why we moved the flush at the end.

2023-09-06 18:46 UTC, kratsg approved these changes
Approved, but with the caveat that this is somewhat impossible to properly force a test force, as it is only catching the scenario of an intermediate callback triggering a garbage-collect.

2023-09-06 19:38 UTC, guitargeek commented
Thanks, @kratsg and @matthewfeickert !

2023-09-06 19:40 UTC, matthewfeickert approved these changes
> Approved, but with the caveat that this is somewhat impossible to properly force a test force, as it is only catching the scenario of an intermediate callback triggering a garbage-collect.

@kratsg if you are also happy to not attempt to figure out a way to deterministically test this then we can just note it in the commit message (I've updated it) and accept this.

Thanks @wernerd-cern and @guitargeek. I'll prepare pyhf `v0.7.4` and get that out before the end of the week.

2023-09-06 19:42 UTC, guitargeek commented
As pointed out by @kratsg, also the new title is maybe not completely appropriate because it's about the skipping of dead weakrefs and not the flushing. Maybe `fix: Skip callbacks with dead weakrefs while iterating over callbacks` would be more appropriate. But not that important after all :)

2023-09-06 19:54 UTC, merged

2023-09-07 04:01 UTC, matthewfeickert commented
@wernerd-cern @guitargeek [`pyhf` `v0.7.4`](https://pypi.org/project/pyhf/0.7.4/) is now out on PyPI with this fix. Thanks!