feat: Allow skipping of validation when combining workspaces
scikit-hep/pyhf pull request #2385
Opened 2023-11-30 10:06 UTC by lorenzennio

# Description

It would be nice to include the option to avoid the validation step when combining two workspaces:
https://github.com/scikit-hep/pyhf/blob/a1a31f17967740c93244f5d9ad17aea1fbef6be3/src/pyhf/workspace.py#L709

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Add validate arg to workspace.combine to allow for optionally skipping
  workspace validation during. Default is to validate.
* Add test for validate arg being used.
* Add Lorenz Gaertner to contributors list.
```

2023-11-30 13:45 UTC, kratsg commented
Is there a reason you want to combine workspaces that don't produce a valid workspace?

2023-11-30 16:27 UTC, lorenzennio commented
Yes, I am working with workspaces that contain instructions for a custom modifier. These don't pass the validation in the first place, but for single workspaces I can simply skip it. Now I want to combine two of them, for a global fit.

2023-12-02 15:35 UTC, kratsg approved these changes

2023-12-03 23:33 UTC, matthewfeickert requested changes

2023-12-03 23:33 UTC, matthewfeickert commented on src/pyhf/workspace.py
> +        return cls(newspec, validate=validate)
This should get covered by a test. I can add that though unless someone beats me to it.

2023-12-03 23:36 UTC, matthewfeickert requested changes
@lorenzennio Can you also [add your name](https://github.com/scikit-hep/pyhf/blob/a1a31f17967740c93244f5d9ad17aea1fbef6be3/CONTRIBUTING.md#pull-request-procedure) to `docs
/contributors.rst` below 

https://github.com/scikit-hep/pyhf/blob/a1a31f17967740c93244f5d9ad17aea1fbef6be3/docs/contributors.rst?plain=1#L35

?

2023-12-07 13:57 UTC, merged